// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaSLlnwpBVyJGpa8ktrpLCY7rFXb1JZeg',
    appId: '1:157160164828:web:c4223a77d4bd5bfed69319',
    messagingSenderId: '157160164828',
    projectId: 'cinemapedia-cc4f4',
    authDomain: 'cinemapedia-cc4f4.firebaseapp.com',
    storageBucket: 'cinemapedia-cc4f4.firebasestorage.app',
    measurementId: 'G-TPEFVJ4EE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1A_Oe1Ith2UOycJgcpD92G_cAR09duWU',
    appId: '1:157160164828:android:98a8797dc5b87eb7d69319',
    messagingSenderId: '157160164828',
    projectId: 'cinemapedia-cc4f4',
    storageBucket: 'cinemapedia-cc4f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZfm2PZQHg4L1eW69_HKM6HupQZFGBzis',
    appId: '1:157160164828:ios:cd6d55049e57593bd69319',
    messagingSenderId: '157160164828',
    projectId: 'cinemapedia-cc4f4',
    storageBucket: 'cinemapedia-cc4f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterE04Cinemapedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZfm2PZQHg4L1eW69_HKM6HupQZFGBzis',
    appId: '1:157160164828:ios:cd6d55049e57593bd69319',
    messagingSenderId: '157160164828',
    projectId: 'cinemapedia-cc4f4',
    storageBucket: 'cinemapedia-cc4f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterE04Cinemapedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaSLlnwpBVyJGpa8ktrpLCY7rFXb1JZeg',
    appId: '1:157160164828:web:7179c8f61efbc398d69319',
    messagingSenderId: '157160164828',
    projectId: 'cinemapedia-cc4f4',
    authDomain: 'cinemapedia-cc4f4.firebaseapp.com',
    storageBucket: 'cinemapedia-cc4f4.firebasestorage.app',
    measurementId: 'G-67R7ZZLPTH',
  );

}